config/routes.rb
Rails.application.routes.draw do

  get 'gifts/index'
  get 'furniture/index'
  get 'kitchen_and_bar/index'
  get 'accessories/index'

  resources :kitchen_and_bars
  resources :accessories
  resources :furnitures
  resources :gifts
  mount Spree::Core::Engine, :at => '/'

  root 'home#index'

end

Spree::Core::Engine.add_routes do
  resources :bridal_registries
  resources :bridal_products, only: [:create, :update, :destroy]
  get '/bridal registry' => 'bridal_registries#default', as: 'default_bridal_registry'
end

app/models/spree/bridal_product.rb
class Spree::BridalProduct < ActiveRecord::Base
  belongs_to :variant
  belongs_to :bridal_registry

  def total
    quantity * variant.price
  end

  def display_total
    Spree::Money.new(total)
  end

end

app/models/spree/bridal_registry.rb
class Spree::BridalRegistry < ActiveRecord::Base
  belongs_to :user, class_name: Spree.user_class
  has_many :bridal_products, dependent: :destroy
  before_create :set_access_hash

  validates :name, presence: true

  def include?(variant_id)
    bridal_products.map(&:variant_id).include? variant_id.to_i
  end

  def to_param
    access_hash
  end
  
  def self.get_by_param(param)
    Spree::BridalRegistry.find_by_access_hash(param)
  end
  
  def can_be_read_by?(user)
    !self.is_private? || user == self.user
  end
  
  def is_default=(value)
    self[:is_default] = value
    return unless is_default?
    Spree::BridalRegistry.where(is_default: true, user_id: user_id).where.not(id: id).update_all(is_default: false)
  end
  
    def is_public?
    !self.is_private?
  end

  private

  def set_access_hash
    random_string = SecureRandom.hex(16)
    self.access_hash = Digest::SHA1.hexdigest("--#{user_id}--#{random_string}--#{Time.now}--")
  end
end

app/controllers/spree/bridal_products_controller.rb
class Spree::BridalProductsController < Spree::StoreController
  respond_to :html

  def create
    @bridal_product = Spree::BridalProduct.new(bridal_product_attributes)
    @bridal_registry = spree_current_user.bridal_registry
    
    if @bridal_registry.include? params[:bridal_product][:variant_id]
      @bridal_product = @bridal_registry.bridal_products.detect { |wp| wp.variant_id == params[:bridal_product][:variant_id].to_i }
    else
      @bridal_product.bridal_registry = spree_current_user.bridal_registry
      @bridal_product.save
    end

    respond_with(@bridal_product) do |format|
      format.html { redirect_to bridal_registry_url(@bridal_registry) }
    end
  end

  def update
    @bridal_product = Spree::BridalProduct.find(params[:id])
    @bridal_product.update_attributes(bridal_product_attributes)

    respond_with(@bridal_product) do |format|
      format.html { redirect_to bridal_registry_url(@bridal_product.bridal_registry) }
    end
  end

  def destroy
    @bridal_product = Spree::BridalProduct.find(params[:id])
    @bridal_product.destroy

    respond_with(@bridal_product) do |format|
      format.html { redirect_to bridal_registry_url(@bridal_product.bridal_registry) }
    end
  end

  private

  def bridal_product_attributes
    params.require(:bridal_product).permit(:variant_id, :bridal_registry_id, :remark, :quantity)
  end
end

app/controllers/spree/bridal_registries_controller.rb
class Spree::BridalRegistriesController < Spree::StoreController
  helper 'spree/products'

  before_action :find_bridal_registry, only: [:destroy, :show, :update, :edit]

  respond_to :html
  respond_to :js, only: :update

  # GET /bridal_registries
  # GET /bridal_registries.json
  def index
    @bridal_registries = spree_current_user.bridal_registries
    respond_with(@bridal_registry)
  end

  # GET /bridal_registries/1
  # GET /bridal_registries/1.json
  def show
    respond_with(@bridal_registry)
  end
  
  def default
    @bridal_registry = spree_current_user.bridal_registry
    respond_with(@bridal_registry) do |format|
      format.html { render :show }
    end
  end

  # GET /bridal_registries/new
  def new
    @bridal_registry = Spree::BridalRegistry.new
    respond_with(@bridal_registry)
  end

  # GET /bridal_registries/1/edit
  def edit
    respond_with(@bridal_registry)
  end

  # POST /bridal_registries
  # POST /bridal_registries.json
  def create
    @bridal_registry = Spree::BridalRegistry.new bridal_registry_attributes
    @bridal_registry.user = spree_current_user
    @bridal_registry.save
    respond_with(@bridal_registry)
  end

  # PATCH/PUT /bridal_registries/1
  # PATCH/PUT /bridal_registries/1.json
  def update
    @bridal_registry.update_attributes bridal_registry_attributes
    respond_with(@bridal_registry)
  end

  # DELETE /bridal_registries/1
  # DELETE /bridal_registries/1.json
  def destroy
    @bridal_registry.destroy
    respond_with(@bridal_registry) do |format|
      format.html { redirect_to account_path }
    end
  end

  private
  def bridal_registry_attributes
    params.require(:bridal_registry).permit(:name, :is_default, :is_private)
  end

  # Isolate this method so it can be overwritten
  def find_bridal_registry
    @bridal_registry = Spree::BridalRegistry.find_by_access_hash!(params[:id])
  end
end

app/controllers/spree/home_controller.rb
module Spree
  class HomeController < Spree::StoreController
    helper 'spree/products'
    respond_to :html

    def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end
    
  end
end

app/helpers/bridal_registries_helper.rb
module BridalRegistriesHelper
end

app/views/spree/bridal_registries/_accessibility.html.erb
<%= form_for @bridal_registry, html: { class: 'ajax_form', id: 'change_bridal_registry_accessibility' } do |f| %>
  <%= f.radio_button :is_private, true %>&nbsp;<%= Spree.t(:private) %>
  <%= f.radio_button :is_private, false %>&nbsp;<%= Spree.t(:public) %>
<% end -%>

app/views/spree/bridal_registries/_mail_to_friend.text.erb
<%= mail.recipient_name %>,

<%= Spree.t(:take_a_look_at_my_bridal_registry) %>

  * <%= bridal_registry.name %>

<% unless mail.message.blank? -%>
<%= mail.message %>
<% end -%>

<%= mail.sender_name %>

<%= Spree.t(:click_link_to_view_bridal_registry, name: bridal_registry.name) %>
<%= bridal_registry_url(bridal_registry) %>

app/views/spree/bridal_registries/edit.html.erb
<div class="container">
  <h1 class="row"><%= Spree.t(:editing_bridal_registry) %></h1>
  <%= form_for @bridal_registry do |f| %>
    <p><%= f.label :name, Spree.t(:name) %>:&nbsp;<%= f.text_field :name %></p>
    <p><%= f.check_box :is_private %>&nbsp;<%= f.label :is_private, Spree.t(:is_private) %></p>
    <p><%= f.check_box :is_default %>&nbsp;<%= f.label :is_default, Spree.t(:is_default) %></p>
    <%= f.submit Spree.t(:update) %>
    <%= Spree.t(:or) %>
    <%= link_to Spree.t(:delete_bridal_registry), @bridal_registry, method: :delete, data: { confirm: 'Are you sure you want to delete this registry?' }, class: 'button' %>
  <% end -%>
</div>

app/views/spree/bridal_registries/index.html.erb
<div class="container">
  <h1 class="row"><%= Spree.t(:bridal_registries) %></h1>
  <%= content_tag :ul do %>
    <% @bridal_registries.each do |br| %>
      <%= content_tag :li do %>
        <%= link_to(br.name, br) %> - <%= bridal_registry.is_private ? Spree.t(:private) : Spree.t(:public) %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/spree/bridal_registries/new.html.erb
<div class="container">
  <h1><%= Spree.t(:creating_bridal_registry) %></h1>
  <%= form_for @bridal_registry do |f| %>
    <p><%= f.label :name, Spree.t(:name) %>:&nbsp;<%= f.text_field :name %></p>
    <p><%= f.check_box :is_private %>&nbsp;<%= f.label :is_private, Spree.t(:is_private) %></p>
    <%= f.submit Spree.t(:create) %>
  <% end -%>
</div>

app/views/spree/bridal_registries/show.html.erb
<div class="container">
<div id="bridal_registry_header" class="row">
  <h1><%= @bridal_registry.name %></h1>
  <% if @bridal_registry.user == spree_current_user %>
    <div id="manage_wishlist_links">
      <%= link_to Spree.t(:edit_bridal_registry), edit_bridal_registry_path(@bridal_registry), class: 'button' %>
    </div>
    <div><%= render partial: 'accessibility' %></div>
  <% end -%>
</div>
<table id="bridal_registry" class="table table-bordered table-hover">
  <thead>
    <tr>
      <% if @bridal_registry.user == spree_current_user %>
        <th><%= Spree.t(:bridal_registry_actions) %></th>
      <% end -%>
      <th><%= Spree.t(:item_view) %></th>
      <th><%= Spree.t(:item_description) %></th>
      <th><%= Spree.t(:availability) %></th>
      <th><%= Spree.t(:date_added) %></th>
      <th><%= Spree.t(:price) %></th>
      <th><%= Spree.t(:quantity) %></th>
      <th><%= Spree.t(:total) %></th>
    </tr>
  </thead>
  <tbody id="line_items">
  <% if @bridal_registry.bridal_products.size > 0 %>
    <% @bridal_registry.bridal_products.each do |wish|
        variant = wish.variant
        product = variant.product %>
    <tr class="<%= cycle('', 'alt') %>">
    <% if @bridal_registry.user == spree_current_user %>
      <td>
        <p><%= link_to Spree.t(:remove_from_bridal_registry), wish, method: :delete, class: 'btn btn-danger' %></p>
        <%= form_for :order, url: populate_orders_url do |f| %>
          <%= hidden_field_tag 'variant_id', variant.id, size: 3 %>
          <%= Spree.t(:quantity) %>
          <%= number_field_tag 'quantity', wish.quantity, size: 3 %>
          <%= link_to Spree.t(:add_to_cart), '#', onclick: '$(this).parent().submit(); return false;', class: 'btn btn-success' %>
        <% end %>
        <% if spree_current_user.bridal_registries.count > 1 %>
          <%= Spree.t(:move_to_another_bridal_registry) %>:
          <%= form_for wish do |f| %>
            <%= f.select :bridal_registry_id, spree_current_user.bridal_registries.map{|br| [br.name, br.id]} %>
            <%= f.submit Spree.t(:move), class: 'btn btn-default' %>
          <% end %>
        <% end %>
        <br />
      </td>
    <% end -%>
      <td>
        <% if variant.images.length == 0 %>
          <%= small_image(variant.product) %>
        <% else %>
          <%= image_tag variant.images.first.attachment.url(:small) %>
        <% end %>
      </td>
      <td>
        <h4><%= link_to product.name, product %></h4>
        <p><%= variant_options variant %></p>
        <%= truncate(strip_tags(product.description), length: 100, omission: '...') %>
      </td>
      <td>
        <%= variant.can_supply? ? Spree.t(:in_stock) : Spree.t(:out_of_stock) %>
      </td>
      <td>
        <%= wish.created_at.strftime '%m/%d/%Y' %>
      </td>
      <td>
        <%= display_price(variant) %>
      </td>
      <td>
        <%= form_for wish do |f| %>
          <%= f.number_field :quantity %>
          <%= f.submit Spree.t('actions.save'), class: 'btn btn-info '  %>
        <% end %>
      </td>
      <td>
        <%= wish.display_total %>
      </td>
    </tr>
    <% end -%>
  <% else -%>
    <tr>
      <td colspan="6"><%= Spree.t(:your_bridal_registry_is_empty) %></td>
    </tr>
  <% end -%>
  </tbody>
</table>
<div class="footer_links" data-hook="wishlist_footer_links">
<% if @bridal_registry.user == spree_current_user %>
  <%= link_to Spree.t(:create_new_bridal_registry), new_bridal_registry_path, class: 'btn btn-default' %>
<% end -%>
<%= link_to Spree.t(:continue_shopping), products_path, class: 'btn btn-default' %>
<% if respond_to?(:email_to_friend_url) %>
  <%= link_to Spree.t('email_to_friend.send_to_friend'), email_to_friend_url('bridal registry', @bridal_registry), class: 'btn btn-default' %>
<% end %>
</div>
</div>