config/routes.rb
Rails.application.routes.draw do

  get 'gifts/index'
  get 'furniture/index'
  get 'kitchen_and_bar/index'
  get 'accessories/index'

  resources :kitchen_and_bars
  resources :accessories
  resources :furnitures
  resources :gifts
  mount Spree::Core::Engine, :at => '/'

  root 'home#index'

end

Spree::Core::Engine.add_routes do
  resources :bridal_registries
  resources :bridal_products, only: [:create, :update, :destroy]
  get '/bridal registry' => 'bridal_registries#default', as: 'default_bridal_registry'
end

app/models/kitchen_and_bar.rb
class KitchenAndBar < ActiveRecord::Base
end

app/controllers/kitchen_and_bars_controller.rb
class KitchenAndBarsController < ApplicationController
  before_action :set_kitchen_and_bar, only: [:show, :edit, :update, :destroy]

  # GET /kitchen_and_bars
  # GET /kitchen_and_bars.json
  def index
    @kitchen_and_bars = KitchenAndBar.all
  end

  # GET /kitchen_and_bars/1
  # GET /kitchen_and_bars/1.json
  def show
  end

  # GET /kitchen_and_bars/new
  def new
    @kitchen_and_bar = KitchenAndBar.new
  end

  # GET /kitchen_and_bars/1/edit
  def edit
  end

  # POST /kitchen_and_bars
  # POST /kitchen_and_bars.json
  def create
    @kitchen_and_bar = KitchenAndBar.new(kitchen_and_bar_params)

    respond_to do |format|
      if @kitchen_and_bar.save
        format.html { redirect_to @kitchen_and_bar, notice: 'Kitchen and bar was successfully created.' }
        format.json { render :show, status: :created, location: @kitchen_and_bar }
      else
        format.html { render :new }
        format.json { render json: @kitchen_and_bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitchen_and_bars/1
  # PATCH/PUT /kitchen_and_bars/1.json
  def update
    respond_to do |format|
      if @kitchen_and_bar.update(kitchen_and_bar_params)
        format.html { redirect_to @kitchen_and_bar, notice: 'Kitchen and bar was successfully updated.' }
        format.json { render :show, status: :ok, location: @kitchen_and_bar }
      else
        format.html { render :edit }
        format.json { render json: @kitchen_and_bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitchen_and_bars/1
  # DELETE /kitchen_and_bars/1.json
  def destroy
    @kitchen_and_bar.destroy
    respond_to do |format|
      format.html { redirect_to kitchen_and_bars_url, notice: 'Kitchen and bar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitchen_and_bar
      @kitchen_and_bar = KitchenAndBar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitchen_and_bar_params
      params[:kitchen_and_bar]
    end
end

app/helpers/kitchen_and_bars_helper.rb
module KitchenAndBarsHelper
end

app/views/kitchen_and_bars/_form.html.erb
<%= form_for(@kitchen_and_bar) do |f| %>
  <% if @kitchen_and_bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitchen_and_bar.errors.count, "error") %> prohibited this kitchen_and_bar from being saved:</h2>

      <ul>
      <% @kitchen_and_bar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kitchen_and_bars/edit.html.erb
<h1>Editing Kitchen And Bar</h1>

<%= render 'form' %>

<%= link_to 'Show', @kitchen_and_bar %> |
<%= link_to 'Back', kitchen_and_bars_path %>

app/views/kitchen_and_bars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kitchen And Bars</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kitchen_and_bars.each do |kitchen_and_bar| %>
      <tr>
        <td><%= link_to 'Show', kitchen_and_bar %></td>
        <td><%= link_to 'Edit', edit_kitchen_and_bar_path(kitchen_and_bar) %></td>
        <td><%= link_to 'Destroy', kitchen_and_bar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kitchen and bar', new_kitchen_and_bar_path %>

app/views/kitchen_and_bars/new.html.erb
<h1>New Kitchen And Bar</h1>

<%= render 'form' %>

<%= link_to 'Back', kitchen_and_bars_path %>

app/views/kitchen_and_bars/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_kitchen_and_bar_path(@kitchen_and_bar) %> |
<%= link_to 'Back', kitchen_and_bars_path %>