config/routes.rb
Rails.application.routes.draw do

  get 'gifts/index'
  get 'furniture/index'
  get 'kitchen_and_bar/index'
  get 'accessories/index'

  resources :kitchen_and_bars
  resources :accessories
  resources :furnitures
  resources :gifts
  mount Spree::Core::Engine, :at => '/'

  root 'home#index'

end

Spree::Core::Engine.add_routes do
  resources :bridal_registries
  resources :bridal_products, only: [:create, :update, :destroy]
  get '/bridal registry' => 'bridal_registries#default', as: 'default_bridal_registry'
end

app/models/accessory.rb
class Accessory < ActiveRecord::Base
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :set_accessory, only: [:show, :edit, :update, :destroy]

  # GET /accessories
  # GET /accessories.json
  def index
    @accessories = Accessory.all
  end

  # GET /accessories/1
  # GET /accessories/1.json
  def show
  end

  # GET /accessories/new
  def new
    @accessory = Accessory.new
  end

  # GET /accessories/1/edit
  def edit
  end

  # POST /accessories
  # POST /accessories.json
  def create
    @accessory = Accessory.new(accessory_params)

    respond_to do |format|
      if @accessory.save
        format.html { redirect_to @accessory, notice: 'Accessory was successfully created.' }
        format.json { render :show, status: :created, location: @accessory }
      else
        format.html { render :new }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accessories/1
  # PATCH/PUT /accessories/1.json
  def update
    respond_to do |format|
      if @accessory.update(accessory_params)
        format.html { redirect_to @accessory, notice: 'Accessory was successfully updated.' }
        format.json { render :show, status: :ok, location: @accessory }
      else
        format.html { render :edit }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accessories/1
  # DELETE /accessories/1.json
  def destroy
    @accessory.destroy
    respond_to do |format|
      format.html { redirect_to accessories_url, notice: 'Accessory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accessory
      @accessory = Accessory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accessory_params
      params[:accessory]
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/views/accessories/_form.html.erb
<%= form_for(@accessory) do |f| %>
  <% if @accessory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accessory.errors.count, "error") %> prohibited this accessory from being saved:</h2>

      <ul>
      <% @accessory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accessories/edit.html.erb
<h1>Editing Accessory</h1>

<%= render 'form' %>

<%= link_to 'Show', @accessory %> |
<%= link_to 'Back', accessories_path %>

app/views/accessories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accessories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accessories.each do |accessory| %>
      <tr>
        <td><%= link_to 'Show', accessory %></td>
        <td><%= link_to 'Edit', edit_accessory_path(accessory) %></td>
        <td><%= link_to 'Destroy', accessory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accessory', new_accessory_path %>

app/views/accessories/new.html.erb
<h1>New Accessory</h1>

<%= render 'form' %>

<%= link_to 'Back', accessories_path %>

app/views/accessories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_accessory_path(@accessory) %> |
<%= link_to 'Back', accessories_path %>