config/routes.rb
Rails.application.routes.draw do

  get 'gifts/index'
  get 'furniture/index'
  get 'kitchen_and_bar/index'
  get 'accessories/index'

  resources :kitchen_and_bars
  resources :accessories
  resources :furnitures
  resources :gifts
  mount Spree::Core::Engine, :at => '/'

  root 'home#index'

end

Spree::Core::Engine.add_routes do
  resources :bridal_registries
  resources :bridal_products, only: [:create, :update, :destroy]
  get '/bridal registry' => 'bridal_registries#default', as: 'default_bridal_registry'
end

app/models/furniture.rb
class Furniture < ActiveRecord::Base
end

app/controllers/furnitures_controller.rb
class FurnituresController < ApplicationController
  before_action :set_furniture, only: [:show, :edit, :update, :destroy]

  # GET /furnitures
  # GET /furnitures.json
  def index
    @furnitures = Furniture.all
  end

  # GET /furnitures/1
  # GET /furnitures/1.json
  def show
  end

  # GET /furnitures/new
  def new
    @furniture = Furniture.new
  end

  # GET /furnitures/1/edit
  def edit
  end

  # POST /furnitures
  # POST /furnitures.json
  def create
    @furniture = Furniture.new(furniture_params)

    respond_to do |format|
      if @furniture.save
        format.html { redirect_to @furniture, notice: 'Furniture was successfully created.' }
        format.json { render :show, status: :created, location: @furniture }
      else
        format.html { render :new }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /furnitures/1
  # PATCH/PUT /furnitures/1.json
  def update
    respond_to do |format|
      if @furniture.update(furniture_params)
        format.html { redirect_to @furniture, notice: 'Furniture was successfully updated.' }
        format.json { render :show, status: :ok, location: @furniture }
      else
        format.html { render :edit }
        format.json { render json: @furniture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /furnitures/1
  # DELETE /furnitures/1.json
  def destroy
    @furniture.destroy
    respond_to do |format|
      format.html { redirect_to furnitures_url, notice: 'Furniture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_furniture
      @furniture = Furniture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def furniture_params
      params[:furniture]
    end
end

app/helpers/furnitures_helper.rb
module FurnituresHelper
end

app/views/furnitures/_form.html.erb
<%= form_for(@furniture) do |f| %>
  <% if @furniture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@furniture.errors.count, "error") %> prohibited this furniture from being saved:</h2>

      <ul>
      <% @furniture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/furnitures/edit.html.erb
<h1>Editing Furniture</h1>

<%= render 'form' %>

<%= link_to 'Show', @furniture %> |
<%= link_to 'Back', furnitures_path %>

app/views/furnitures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Furnitures</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @furnitures.each do |furniture| %>
      <tr>
        <td><%= link_to 'Show', furniture %></td>
        <td><%= link_to 'Edit', edit_furniture_path(furniture) %></td>
        <td><%= link_to 'Destroy', furniture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Furniture', new_furniture_path %>

app/views/furnitures/new.html.erb
<h1>New Furniture</h1>

<%= render 'form' %>

<%= link_to 'Back', furnitures_path %>

app/views/furnitures/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_furniture_path(@furniture) %> |
<%= link_to 'Back', furnitures_path %>